### ISSUE TITLE
Contact Details

### ISSUE THREAD

**Issue by vianraaa** [goodpaul6/Tiny#21]
It appears that you don't have any contact details on your profile nor your repositories. I'm currently writing a kernel in C and using Tiny as the scripting language for apps and drivers. It would be awesome if I could talk to you if I encounter any issues. Thanks!

**Comment by goodpaul6** [comment]
@nexacopic Sounds very cool! You can email me at apaar186@gmail.com, though it's probably best to open issues here if you have any concerns pertaining to Tiny.
