### ISSUE TITLE
License

### ISSUE THREAD

**Issue by KellerMartins** [goodpaul6/Tiny#3]
Is the project missing a license file or is this intended?
Because as stated on [choosealicense.com/no-permission](https://choosealicense.com/no-permission/), the lack of it implies I can't use or modify the code.

I've been thinking of using this language in a project, but first I wanted to make sure it's ok to use it, in case I decide to share the source code later.

**Comment by goodpaul6** [comment]
Oh! Thanks for reminding me! I’ll add a license file.

**Comment by goodpaul6** [comment]
@KellerMartins Okay, I've added a license file. Please let me know if you have any issues with the language :)
